# Generated by Django 5.0.3 on 2024-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=256, null=True)),
                ('year_passing', models.CharField(max_length=50)),
                ('hiring_process', models.CharField(choices=[('Walk In Drive', 'Walk In'), ('OFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('job_discription', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('offical_site', models.TextField(blank=True, null=True)),
                ('apply_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
