# Generated by Django 5.0.3 on 2024-03-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
    ]
