# Generated by Django 5.0.3 on 2024-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_posts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
