# Generated by Django 5.0.3 on 2024-03-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_posts_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='more_info',
        ),
    ]
