# Generated by Django 5.0.3 on 2024-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_posts_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
